"""
Clang / LLVM -Rpass optimization remark parser.

Clang emits remarks with:
    clang -O3 -Rpass=loop-vectorize -Rpass-missed=loop-vectorize \\
               -Rpass-analysis=loop-vectorize solver.c

Output (YAML-style or text):
    solver.c:42:5: remark: vectorized loop (vectorization width: 8, ...) [-Rpass=loop-vectorize]
    solver.c:87:9: remark: loop not vectorized: cannot identify array bounds [-Rpass-missed=loop-vectorize]

Also parses Intel ICX/IFORT .optrpt (optimization report) files generated by:
    icx -O3 -qopt-report=5 -qopt-report-file=solver.optrpt solver.c
"""

from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any, Optional

import yaml

from perflens.compiler_feedback.models import (
    CompilerFeedbackReport,
    CompilerRemark,
    FeedbackKind,
)

# ── Clang text remark ─────────────────────────────────────────────────────────

_CLANG_REMARK = re.compile(
    r"^(?P<file>[^:]+):(?P<line>\d+):(?P<col>\d+):\s+remark:\s+"
    r"(?P<msg>.+?)\s+\[-R(?:pass|pass-missed|pass-analysis)=(?P<pass>[^\]]+)\]"
)
_CLANG_MISSED = re.compile(r"-Rpass-missed=")


class _OptimizationRecordLoader(yaml.SafeLoader):
    pass


def _construct_optimization_record(
    loader: Any, tag_suffix: str, node: Any
) -> dict[str, Any]:
    record = loader.construct_mapping(node, deep=True)
    record["_record_type"] = tag_suffix
    return record


_OptimizationRecordLoader.add_multi_constructor(
    "!", _construct_optimization_record
)

# ── Intel ICX .optrpt ─────────────────────────────────────────────────────────

_ICX_LOOP_HEADER = re.compile(
    r"LOOP BEGIN at (?P<file>[^(]+)\((?P<line>\d+),(?P<col>\d+)\)"
)
_ICX_VECTORIZED = re.compile(
    r"<Peeled loop for vectorization>|LOOP WAS VECTORIZED|vector width simd"
    r"|remark #15301: PERMUTED LOOP WAS VECTORIZED",
    re.IGNORECASE,
)
_ICX_NOT_VECTORIZED = re.compile(
    r"LOOP WAS NOT VECTORIZED|remark #15344|remark #15382|remark #25439",
    re.IGNORECASE,
)
_ICX_REASON = re.compile(r"remark #\d+:\s+(.+)")


class ClangFeedbackParser:
    """Parse Clang -Rpass remarks from text output or compile live."""

    def parse_file(self, path: Path, source: Path) -> CompilerFeedbackReport:
        return self._parse_text(path.read_text(errors="replace"), source)

    def compile_and_parse(
        self,
        source: Path,
        extra_flags: Optional[list[str]] = None,
        compiler: str = "clang",
    ) -> CompilerFeedbackReport:
        if not shutil.which(compiler):
            return CompilerFeedbackReport(source=source, compiler=compiler)

        flags = [
            "-O3", "-march=native", "-fopenmp",
            "-Rpass=loop-vectorize",
            "-Rpass-missed=loop-vectorize",
            "-Rpass-analysis=loop-vectorize",
            "-Rpass=inline",
            "-fsave-optimization-record",
        ] + (extra_flags or [])

        with tempfile.TemporaryDirectory() as tmpdir:
            obj = Path(tmpdir) / "output.o"
            record_path = Path(tmpdir) / "optimization.opt.yaml"
            record_flags = flags + [f"-foptimization-record-file={record_path}"]
            cmd = [compiler] + record_flags + ["-c", str(source), "-o", str(obj)]
            try:
                proc = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
                text = proc.stderr   # Clang remarks go to stderr
            except subprocess.TimeoutExpired:
                return CompilerFeedbackReport(source=source, compiler=compiler)

            report = self._parse_text(text, source)
            if (
                not report.vectorized_loops
                and not report.missed_vectorization
                and record_path.exists()
            ):
                report = self._parse_yaml(record_path, source)
            report.flags_used = record_flags
            return report

    def _parse_yaml(self, path: Path, source: Path) -> CompilerFeedbackReport:
        remarks: list[CompilerRemark] = []
        with path.open(errors="replace") as stream:
            for record in yaml.load_all(stream, Loader=_OptimizationRecordLoader):
                if not isinstance(record, dict):
                    continue
                if record.get("Pass") != "loop-vectorize":
                    continue

                debug_loc = record.get("DebugLoc") or {}
                if not isinstance(debug_loc, dict):
                    debug_loc = {}
                record_type = record.get("_record_type")
                if record_type == "Passed":
                    kind = FeedbackKind.VECTORIZED
                elif record_type == "Missed":
                    kind = FeedbackKind.NOT_VECTORIZED
                elif record_type == "Analysis":
                    kind = FeedbackKind.GENERAL
                else:
                    continue

                message = str(record.get("Name") or "loop-vectorize")
                args = record.get("Args")
                if args:
                    message += f": {args}"
                remarks.append(CompilerRemark(
                    source_file=str(debug_loc.get("File") or source),
                    line=int(debug_loc.get("Line") or 0),
                    col=int(debug_loc.get("Column") or 0),
                    kind=kind,
                    compiler="clang",
                    pass_name="loop-vectorize",
                    message=message,
                ))

        return CompilerFeedbackReport(
            source=source,
            compiler="clang",
            remarks=sorted(remarks, key=lambda r: r.line),
        )

    def _parse_text(self, text: str, source: Path) -> CompilerFeedbackReport:
        remarks: list[CompilerRemark] = []
        for raw_line in text.splitlines():
            m = _CLANG_REMARK.match(raw_line.strip())
            if not m:
                continue
            msg      = m.group("msg")
            pass_nm  = m.group("pass")
            missed   = "missed" in raw_line.lower() or "not vectorized" in msg.lower()
            kind     = FeedbackKind.NOT_VECTORIZED if missed else FeedbackKind.VECTORIZED
            if "inline" in pass_nm:
                kind = FeedbackKind.NOT_INLINED if missed else FeedbackKind.INLINED
            if "alias" in msg.lower() or "restrict" in msg.lower():
                kind = FeedbackKind.ALIAS_CHECK
            if "dependence" in msg.lower() or "dependency" in msg.lower():
                kind = FeedbackKind.DEPENDENCY

            remarks.append(CompilerRemark(
                source_file=m.group("file"),
                line=int(m.group("line")),
                col=int(m.group("col")),
                kind=kind,
                compiler="clang",
                pass_name=pass_nm,
                message=msg,
            ))

        return CompilerFeedbackReport(
            source=source, compiler="clang",
            remarks=sorted(remarks, key=lambda r: r.line),
        )


class ICXFeedbackParser:
    """
    Parse Intel ICX / IFORT optimization reports (.optrpt files).

    Generate with:
        icx -O3 -xCORE-AVX512 -qopt-report=5 \\
            -qopt-report-file=solver.optrpt solver.c
    """

    def parse_file(self, path: Path, source: Path) -> CompilerFeedbackReport:
        return self._parse_text(path.read_text(errors="replace"), source)

    def compile_and_parse(
        self,
        source: Path,
        extra_flags: Optional[list[str]] = None,
        compiler: str = "icx",
    ) -> CompilerFeedbackReport:
        if not shutil.which(compiler):
            return CompilerFeedbackReport(source=source, compiler=compiler)

        with tempfile.TemporaryDirectory() as tmpdir:
            optrpt = Path(tmpdir) / "report.optrpt"
            flags  = [
                "-O3", "-xCORE-AVX512", "-fopenmp",
                "-qopt-report=5",
                f"-qopt-report-file={optrpt}",
            ] + (extra_flags or [])
            cmd = [compiler] + flags + ["-c", str(source)]
            try:
                subprocess.run(cmd, capture_output=True, timeout=90, cwd=tmpdir)
            except subprocess.TimeoutExpired:
                return CompilerFeedbackReport(source=source, compiler=compiler)

            if optrpt.exists():
                report = self._parse_text(optrpt.read_text(errors="replace"), source)
                report.flags_used = flags
                return report

        return CompilerFeedbackReport(source=source, compiler=compiler)

    def _parse_text(self, text: str, source: Path) -> CompilerFeedbackReport:
        remarks: list[CompilerRemark] = []
        current_line = 0

        for raw_line in text.splitlines():
            lh = _ICX_LOOP_HEADER.search(raw_line)
            if lh:
                current_line = int(lh.group("line"))
                continue

            if current_line == 0:
                continue

            if _ICX_VECTORIZED.search(raw_line) and not _ICX_NOT_VECTORIZED.search(raw_line):
                remarks.append(CompilerRemark(
                    source_file=str(source),
                    line=current_line, col=0,
                    kind=FeedbackKind.VECTORIZED,
                    compiler="icx",
                    pass_name="loop-vectorize",
                    message=raw_line.strip(),
                ))
            elif _ICX_NOT_VECTORIZED.search(raw_line):
                reason_m = _ICX_REASON.search(raw_line)
                msg = reason_m.group(1) if reason_m else raw_line.strip()
                kind = FeedbackKind.ALIAS_CHECK if "alias" in msg.lower() else FeedbackKind.NOT_VECTORIZED
                remarks.append(CompilerRemark(
                    source_file=str(source),
                    line=current_line, col=0,
                    kind=kind,
                    compiler="icx",
                    pass_name="loop-vectorize",
                    message=msg,
                ))

        return CompilerFeedbackReport(
            source=source, compiler="icx",
            remarks=sorted(remarks, key=lambda r: r.line),
        )
