"""Unit tests for perflens.profiler — VTune and HPCToolkit parsers."""

from __future__ import annotations

import textwrap
from pathlib import Path

import pytest

from perflens.profiler.dispatcher import parse_profile
from perflens.profiler.models import Hotspot, ProfileData
from perflens.profiler.vtune_parser import VTuneParser
from perflens.profiler.hpctoolkit_parser import HPCToolkitParser


# ── VTune CSV ─────────────────────────────────────────────────────────────────

VTUNE_CSV_SIMPLE = textwrap.dedent("""\
    Function,Module,CPU Time,CPU Time (%),CPI Rate,L3 Cache Miss Rate,Memory Bound (%)
    compute_flux,libsolver.so,2500.5,45.3,1.82,0.12,62.1
    update_wetcells,libsolver.so,1200.0,21.7,1.21,0.03,18.4
    _start,solver,50.0,0.9,0.95,,
    MPI_Waitall,libmpi.so,800.0,14.5,,,
""")

VTUNE_CSV_WITH_METADATA = textwrap.dedent("""\
    # VTune Profiler Report
    # Report: Hotspots
    # Date: 2025-06-01
    Function (Full),Module,Source File,Start Line,CPU Time (ms),CPI,Vectorization (%),Arithmetic Intensity
    compute_flux,solver,src/solver.c,142,3200.0,1.82,72.4,1.85
    extrapolate_second_order,solver,src/extrapolate.c,87,1800.0,2.14,41.2,0.42
    update_conserved,solver,src/update.c,201,950.0,1.05,88.1,3.21
""")


def _write(tmp_path: Path, name: str, text: str) -> Path:
    p = tmp_path / name
    p.write_text(text)
    return p


def test_vtune_csv_basic(tmp_path):
    csv = _write(tmp_path, "report.csv", VTUNE_CSV_SIMPLE)
    pd = VTuneParser().parse(report_path=csv)
    assert pd.tool == "vtune"
    assert len(pd.hotspots) >= 3
    # Top hotspot should be compute_flux
    top = pd.top_hotspots(1)[0]
    assert "compute_flux" in top.function or top.cpu_time_ms >= 2000


def test_vtune_csv_cpi_parsed(tmp_path):
    csv = _write(tmp_path, "report.csv", VTUNE_CSV_SIMPLE)
    pd = VTuneParser().parse(report_path=csv)
    hotspot = next((h for h in pd.hotspots if "compute_flux" in h.function), None)
    assert hotspot is not None
    assert hotspot.cpi is not None
    assert abs(hotspot.cpi - 1.82) < 0.01


def test_vtune_csv_percentages_sum_approx_100(tmp_path):
    csv = _write(tmp_path, "report.csv", VTUNE_CSV_SIMPLE)
    pd = VTuneParser().parse(report_path=csv)
    total_pct = sum(h.cpu_time_pct for h in pd.hotspots)
    # Should be ~100% (may be slightly off due to rounding/incomplete data)
    assert 80.0 <= total_pct <= 120.0


def test_vtune_csv_with_metadata_header(tmp_path):
    """Parser should skip comment/metadata lines and find the real header."""
    csv = _write(tmp_path, "report2.csv", VTUNE_CSV_WITH_METADATA)
    pd = VTuneParser().parse(report_path=csv)
    assert len(pd.hotspots) >= 2


def test_vtune_csv_arithmetic_intensity(tmp_path):
    csv = _write(tmp_path, "report3.csv", VTUNE_CSV_WITH_METADATA)
    pd = VTuneParser().parse(report_path=csv)
    ai_hotspots = [h for h in pd.hotspots if h.arithmetic_intensity is not None]
    assert len(ai_hotspots) >= 1


def test_vtune_no_report_returns_empty():
    pd = VTuneParser().parse(report_path=None)
    assert pd.total_time_ms == 0.0
    assert pd.hotspots == []


def test_vtune_nonexistent_path_raises(tmp_path):
    with pytest.raises(Exception):
        VTuneParser().parse(report_path=tmp_path / "nonexistent.csv")


# ── VTune XML ─────────────────────────────────────────────────────────────────

VTUNE_XML = textwrap.dedent("""\
    <?xml version="1.0" encoding="UTF-8"?>
    <report>
      <functions>
        <function name="compute_flux" module="solver" startLine="142" cpuTime="3200.0"
                  cpiRate="1.82" l3CacheMissRate="12.0" memoryBound="62.1" vectorizationPct="72.4"/>
        <function name="extrapolate" module="solver" startLine="87" cpuTime="1800.0"
                  cpiRate="2.14" l3CacheMissRate="3.0" memoryBound="18.4"/>
      </functions>
    </report>
""")


def test_vtune_xml_basic(tmp_path):
    xml = _write(tmp_path, "report.xml", VTUNE_XML)
    pd = VTuneParser().parse(report_path=xml)
    assert len(pd.hotspots) == 2
    assert pd.total_time_ms == 5000.0


def test_vtune_xml_cpi(tmp_path):
    xml = _write(tmp_path, "report.xml", VTUNE_XML)
    pd = VTuneParser().parse(report_path=xml)
    h = next(h for h in pd.hotspots if "compute_flux" in h.function)
    assert abs(h.cpi - 1.82) < 0.01


# ── HPCToolkit ────────────────────────────────────────────────────────────────

HPCTOOLKIT_CSV = textwrap.dedent("""\
    # HPCToolkit Profile
    # Generated by hpcproftt
    Procedure,Inclusive Time (ms),Module,File,Line
    compute_flux,4100.0,solver,src/solver.c,142
    update_wetcells,1900.0,solver,src/update.c,67
    MPI_Waitall,300.0,libmpi.so,,
""")


def test_hpctoolkit_csv_basic(tmp_path):
    csv = _write(tmp_path, "hpc.csv", HPCTOOLKIT_CSV)
    pd = HPCToolkitParser().parse(report_path=csv)
    assert pd.tool == "hpctoolkit"
    assert len(pd.hotspots) >= 2


def test_hpctoolkit_csv_top_hotspot(tmp_path):
    csv = _write(tmp_path, "hpc.csv", HPCTOOLKIT_CSV)
    pd = HPCToolkitParser().parse(report_path=csv)
    top = pd.top_hotspots(1)[0]
    assert "compute_flux" in top.function


def test_hpctoolkit_percentages(tmp_path):
    csv = _write(tmp_path, "hpc.csv", HPCTOOLKIT_CSV)
    pd = HPCToolkitParser().parse(report_path=csv)
    total_pct = sum(h.cpu_time_pct for h in pd.hotspots)
    assert abs(total_pct - 100.0) < 0.1


# ── Dispatcher ────────────────────────────────────────────────────────────────

def test_dispatcher_vtune(tmp_path):
    csv = _write(tmp_path, "report.csv", VTUNE_CSV_SIMPLE)
    pd = parse_profile(tool="vtune", report_path=csv)
    assert pd.tool == "vtune"


def test_dispatcher_hpctoolkit(tmp_path):
    csv = _write(tmp_path, "hpc.csv", HPCTOOLKIT_CSV)
    pd = parse_profile(tool="hpctoolkit", report_path=csv)
    assert pd.tool == "hpctoolkit"


def test_dispatcher_unknown_tool(tmp_path):
    with pytest.raises(ValueError, match="Unknown profiling tool"):
        parse_profile(tool="amplxe", report_path=None)


# ── ProfileData model ─────────────────────────────────────────────────────────

def test_profiledata_top_hotspots_sorted():
    pd = ProfileData(
        tool="vtune", source=None, report_path=None, total_time_ms=1000.0,
        hotspots=[
            Hotspot("a", "", None, 0, 10.0, 100.0, None, None, None, None, None, None, None),
            Hotspot("b", "", None, 0, 80.0, 800.0, None, None, None, None, None, None, None),
            Hotspot("c", "", None, 0, 10.0, 100.0, None, None, None, None, None, None, None),
        ],
    )
    top = pd.top_hotspots(2)
    assert top[0].function == "b"
    assert len(top) == 2


def test_profiledata_to_dict():
    import json
    pd = ProfileData(
        tool="vtune", source=None, report_path=None, total_time_ms=5000.0,
        hotspots=[Hotspot("flux", "solver", "solver.c", 142, 60.0, 3000.0,
                          1.8, 0.12, 0.62, 0.15, 0.72, 8.5, 1.85)],
    )
    d = pd.to_dict()
    json.dumps(d)   # must be serialisable
    assert d["total_time_ms"] == 5000.0
    assert len(d["hotspots"]) == 1


def test_hotspot_to_dict():
    h = Hotspot("flux", "solver", "solver.c", 142, 45.3, 2500.5,
                1.82, 0.12, 0.62, 0.18, 0.72, 9.1, 1.85)
    d = h.to_dict()
    assert d["function"] == "flux"
    assert d["cpu_time_ms"] == 2500.5
